//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPax
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTPConfig
    {
        public string IP { get; set; }
        public string FTP { get; set; }
        public string Folder { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int FTP_ID { get; set; }
    }
}
