//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPax
{
    using System;
    using System.Collections.Generic;
    
    public partial class menuStructure
    {
        public int Menuid { get; set; }
        public string MenuDesc { get; set; }
        public string ExeFile { get; set; }
        public string ApplicationType { get; set; }
        public Nullable<int> Position { get; set; }
        public int PackageID { get; set; }
    }
}
